import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

const vt323 = localFont({
  src: "../../assets/fonts/VT323/VT323-Regular.ttf",
  variable: "--font-vt323",
});

const pixelifySans = localFont({
  src: "../../assets/fonts/Pixelify_Sans/PixelifySans-VariableFont_wght.ttf",
  variable: "--font-pixelify-sans",
});

export const metadata: Metadata = {
  title: "Pixugo",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/pixugo-logo-icon.png",
    shortcut: "/favicon.ico",
    apple: "/icons/pixugo-logo-icon.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vt323.variable} ${pixelifySans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
