import type { Metadata } from "next";
import { VT323, Pixelify_Sans } from "next/font/google";
import Sidebar from "@/app/dashboard/components/sidebar/page";
import "@/styles/globals.css";

const vt323 = VT323({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-vt323",
  display: "swap",
}); 

const pixelifySans = Pixelify_Sans({
    variable: "--font-pixelify-sans",
    subsets: ["latin"],
    display: "swap",    
});

export const metadata: Metadata = {
    title: "Pixugo",
    description: "Generated by create next app",
    icons: {
        icon: [

        ]
    }
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${vt323.variable} ${pixelifySans.variable} antialiased`}>
            <Sidebar />
            {children}
        </div>
    );
}
