import type { Metadata } from "next";
import Sidebar from "@/app/dashboard/components/sidebar/page";
import "@/styles/globals.css";

export const metadata: Metadata = {
    title: "Pixugo",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`antialiased`}>
            <Sidebar />
            {children}
        </div>
    );
}
